### ISSUE TITLE
Simplify prompt

### ISSUE THREAD

**Issue by henrikmdev** [laurkp/hangman#4]
https://github.com/laurkp/hangman/blob/e0d23bc2eded19e265dba2feef7d83c921fb06e7/hangman/Program.cs#L25
https://github.com/laurkp/hangman/blob/e0d23bc2eded19e265dba2feef7d83c921fb06e7/hangman/Program.cs#L71

These two lines look very similar. Might there be a way you can modify your code to do this once instead of twice?

**Comment by henrikmdev** [comment]
I would just get rid of the first one and move line 71 to the beginning of your while loop.

**Comment by incredibleLeitman** [comment]
@laurkp Do you even understand what 
```
string.Join("", mysteryWord.Select(c => "_")
```
actually does and how this works?

I'll suggest you come up with a block that prints the letters and placeholders by yourself with code that you understand first,
using the tools that you know.
